# Generated by Django 5.0.6 on 2024-06-26 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Time_Manager', '0003_routine'),
    ]

    operations = [
        migrations.RenameField(
            model_name='routine',
            old_name='description',
            new_name='instruction',
        ),
    ]
