# Generated by Django 5.0.6 on 2024-06-27 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Time_Manager', '0004_rename_description_routine_instruction'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('completed', models.BooleanField(default=False)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_goals', models.ManyToManyField(blank=True, to='Time_Manager.dailygoal')),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('completed', models.BooleanField(default=False)),
                ('month', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('completed', models.BooleanField(default=False)),
                ('week_start_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='YearlyGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('completed', models.BooleanField(default=False)),
                ('year', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='DailyGoals',
        ),
        migrations.DeleteModel(
            name='MonthlyGoals',
        ),
        migrations.DeleteModel(
            name='WeeklyGoals',
        ),
        migrations.AddField(
            model_name='goal',
            name='monthly_goals',
            field=models.ManyToManyField(blank=True, to='Time_Manager.monthlygoal'),
        ),
        migrations.AddField(
            model_name='goal',
            name='weekly_goals',
            field=models.ManyToManyField(blank=True, to='Time_Manager.weeklygoal'),
        ),
        migrations.AddField(
            model_name='goal',
            name='yearly_goals',
            field=models.ManyToManyField(blank=True, to='Time_Manager.yearlygoal'),
        ),
    ]
