# Generated by Django 5.0.6 on 2024-06-27 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Time_Manager', '0005_dailygoal_goal_monthlygoal_weeklygoal_yearlygoal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='dailygoal',
            name='description',
        ),
        migrations.RemoveField(
            model_name='dailygoal',
            name='name',
        ),
        migrations.RemoveField(
            model_name='monthlygoal',
            name='description',
        ),
        migrations.RemoveField(
            model_name='monthlygoal',
            name='name',
        ),
        migrations.RemoveField(
            model_name='weeklygoal',
            name='description',
        ),
        migrations.RemoveField(
            model_name='weeklygoal',
            name='name',
        ),
        migrations.RemoveField(
            model_name='weeklygoal',
            name='week_start_date',
        ),
        migrations.RemoveField(
            model_name='yearlygoal',
            name='description',
        ),
        migrations.RemoveField(
            model_name='yearlygoal',
            name='name',
        ),
        migrations.AddField(
            model_name='dailygoal',
            name='task',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dailygoal',
            name='weekly_goal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_goals', to='Time_Manager.weeklygoal'),
        ),
        migrations.AddField(
            model_name='monthlygoal',
            name='task',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='monthlygoal',
            name='yearly_goal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monthly_goals', to='Time_Manager.yearlygoal'),
        ),
        migrations.AddField(
            model_name='weeklygoal',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='weeklygoal',
            name='monthly_goal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weekly_goals', to='Time_Manager.monthlygoal'),
        ),
        migrations.AddField(
            model_name='weeklygoal',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='weeklygoal',
            name='task',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='yearlygoal',
            name='task',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dailygoal',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='monthlygoal',
            name='month',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='yearlygoal',
            name='year',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='yearlygoal',
            name='goals',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='yearly_goals', to='Time_Manager.goals'),
        ),
        migrations.DeleteModel(
            name='Goal',
        ),
    ]
