# Generated by Django 5.0.6 on 2024-07-10 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Time_Manager', '0007_customperiodgoal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomPeriodGoal',
        ),
    ]
