# Generated by Django 5.0.6 on 2024-07-15 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Time_Manager', '0008_delete_customperiodgoal'),
    ]

    operations = [
        migrations.AddField(
            model_name='routine',
            name='is_weekend',
            field=models.BooleanField(default=False),
        ),
    ]
