# Generated by Django 5.0.6 on 2024-07-15 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Time_Manager', '0009_routine_is_weekend'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailygoal',
            old_name='task',
            new_name='goal',
        ),
        migrations.RenameField(
            model_name='monthlygoal',
            old_name='task',
            new_name='goal',
        ),
        migrations.RenameField(
            model_name='weeklygoal',
            old_name='task',
            new_name='goal',
        ),
        migrations.RenameField(
            model_name='yearlygoal',
            old_name='task',
            new_name='goal',
        ),
        migrations.AddField(
            model_name='dailygoal',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='monthlygoal',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='weeklygoal',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='yearlygoal',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
