# Generated by Django 5.0.6 on 2024-07-18 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Time_Manager', '0013_alter_routine_options_goals_end_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailygoal',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='dailygoal',
            name='start_time',
            field=models.TimeField(null=True),
        ),
    ]
