# Generated by Django 5.1.4 on 2025-01-28 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Time_Manager', '0015_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailygoal',
            name='weekly_goal',
        ),
        migrations.CreateModel(
            name='DayGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(null=True)),
                ('completed', models.BooleanField(default=False)),
                ('date', models.DateField(null=True)),
                ('start_time', models.TimeField(null=True)),
                ('end_time', models.TimeField(null=True)),
                ('weekly_goal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day_goals', to='Time_Manager.weeklygoal')),
            ],
        ),
        migrations.AddField(
            model_name='dailygoal',
            name='day_goal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_goals', to='Time_Manager.daygoal'),
        ),
    ]
