# Generated by Django 5.1.4 on 2025-01-28 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Time_Manager', '0016_remove_dailygoal_weekly_goal_daygoal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daygoal',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='daygoal',
            name='start_time',
        ),
        migrations.AlterField(
            model_name='daygoal',
            name='weekly_goal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day_goal', to='Time_Manager.weeklygoal'),
        ),
    ]
