# Generated by Django 5.1.4 on 2025-01-29 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Time_Manager', '0017_remove_daygoal_end_time_remove_daygoal_start_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='routine',
            name='days_of_week',
            field=models.JSONField(default=list),
        ),
    ]
