# Generated by Django 5.1.5 on 2025-07-14 07:52

from django.db import migrations

def set_default_user(apps, schema_editor):
    Routine = apps.get_model('Time_Manager', 'Routine')
    User = apps.get_model('auth', 'User')
    default_user = User.objects.first()  # Or use any logic to get a default user
    
    for routine in Routine.objects.filter(user__isnull=True):
        routine.user = default_user
        routine.save()

class Migration(migrations.Migration):
    dependencies = [
        ('Time_Manager', '0020_event_end_time_event_start_time'),
    ]
    
    operations = [
        migrations.RunPython(set_default_user),
    ]