# Generated by Django 5.1.5 on 2025-07-14 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Time_Manager', '0021_set_user_for_existing_routines'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='routine',
            options={},
        ),
        migrations.AddField(
            model_name='routine',
            name='is_split',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='routine',
            name='original_routine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Time_Manager.routine'),
        ),
    ]
