# Generated by Django 5.1.5 on 2025-02-03 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_profile_delete_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_img',
            field=models.ImageField(blank=True, default='profile1.1.png', null=True, upload_to='profiles/'),
        ),
    ]
