# Generated by Codex on 2026-06-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0002_category_timestamps_rename_item_type_item_timestamps'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(
                choices=[
                    ('box', 'General'),
                    ('laptop', 'Computers'),
                    ('mobile-screen-button', 'Phones'),
                    ('tv', 'Electronics'),
                    ('car', 'Vehicles'),
                    ('house', 'Property'),
                    ('shirt', 'Clothing'),
                    ('couch', 'Furniture'),
                    ('screwdriver-wrench', 'Tools'),
                    ('file', 'Documents'),
                    ('book', 'Books'),
                    ('kitchen-set', 'Kitchen'),
                    ('dumbbell', 'Sports & Fitness'),
                    ('gem', 'Jewelry & Valuables'),
                    ('paw', 'Pets'),
                    ('gamepad', 'Games & Hobbies'),
                ],
                default='box',
                help_text='Pick an icon that represents this category, or upload a custom image below.',
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(
                blank=True,
                help_text='Optional custom image — overrides the icon when set.',
                null=True,
                upload_to='inventory/categories/',
            ),
        ),
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(
                blank=True,
                help_text='A photo of the item — snap one live or upload a file.',
                null=True,
                upload_to='inventory/items/',
            ),
        ),
    ]
