# Generated by Django 5.1.5 on 2025-06-30 17:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_date', models.DateField(auto_now_add=True)),
                ('time_of_day', models.DateTimeField(auto_now_add=True)),
                ('entry', models.TextField(null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='journal_entry', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
