# Generated by Django 5.1.5 on 2025-07-01 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WellBeing', '0002_alter_journalentry_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='days_date',
            field=models.DateField(),
        ),
    ]
