# Generated by Django 5.1.5 on 2025-07-01 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WellBeing', '0003_alter_journalentry_days_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='time_of_day',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
