# Generated by Django 5.1.5 on 2025-07-14 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WellBeing', '0004_alter_journalentry_time_of_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='journal/audio/'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='journal/documents/'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='journal/images/'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='journal/videos/'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='entry',
            field=models.TextField(blank=True, null=True),
        ),
    ]
