# Generated by Django 5.1.5 on 2026-06-17 21:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WellBeing', '0005_journalentry_audio_journalentry_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='energy',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Physical and mental energy levels today.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='focus',
            field=models.PositiveSmallIntegerField(blank=True, help_text='How clear-headed and focused you felt.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='mood',
            field=models.PositiveSmallIntegerField(blank=True, help_text='How are you feeling overall? 1 = rough day, 5 = great day.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='needs_improvement',
            field=models.TextField(blank=True, help_text='What needs improvement?', null=True),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='sleep_hours',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Hours of sleep last night.', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='went_well',
            field=models.TextField(blank=True, help_text='What went well today?', null=True),
        ),
    ]
